compcert: use of undeclared identifier __FUNCTION__
a compiler extension.
Only half-way through: compcert throws
Fatal error: uncaught exception Stack overflow
Raised by primitive operation at Debugvar.join.join2 in file "extraction/Debugvar.ml", line 196, characters 36-57
even with all __FUNCTION__ removed.

But still good to catch C11 extensions, like anonymous structs/unions
(which are also problematic for tcc dwarf support).